package memory

import "fmt"

// migrate creates all tables, indexes, and FTS5 virtual tables.
// Idempotent: uses IF NOT EXISTS on every statement.
func (s *SQLiteStore) migrate() error {
	s.mu.Lock()
	defer s.mu.Unlock()

	migrations := []string{

		// ── facts (L1 semantic memory) ──
		`CREATE TABLE IF NOT EXISTS facts (
			id               INTEGER PRIMARY KEY AUTOINCREMENT,
			schema_version   INTEGER NOT NULL DEFAULT 1,
			entity           TEXT    NOT NULL DEFAULT 'master',
			relation_type    TEXT    NOT NULL DEFAULT '',
			content          TEXT    NOT NULL DEFAULT '',
			source_tier      TEXT    NOT NULL DEFAULT 'explicit',
			temporal_scope   TEXT    NOT NULL DEFAULT 'pattern',
			auto_expire_days INTEGER NOT NULL DEFAULT 0,
			observation_count INTEGER NOT NULL DEFAULT 0,
			importance       INTEGER NOT NULL DEFAULT 5,
			evidence         TEXT    NOT NULL DEFAULT '{}',
			oscillating      INTEGER NOT NULL DEFAULT 0,
			suppress_until   INTEGER NOT NULL DEFAULT 0,
			mention_count    INTEGER NOT NULL DEFAULT 0,
			vector           BLOB,
			recall_count     INTEGER NOT NULL DEFAULT 0,
			last_recalled_at INTEGER NOT NULL DEFAULT 0,
			context_tags     TEXT    NOT NULL DEFAULT '[]',
			source           TEXT    NOT NULL DEFAULT 'chat',
			memcell_type     TEXT    NOT NULL DEFAULT 'fact',
			episode_id       INTEGER DEFAULT NULL,
			archived         INTEGER NOT NULL DEFAULT 0,

			-- v2.1: SignalDetection drain + absorption tracking
			signal_processed INTEGER NOT NULL DEFAULT 1,
			absorbed         INTEGER NOT NULL DEFAULT 0,

			-- v2.1: embedding cache (avoid re-embedding same text)
			embedding_text_sha256 TEXT NOT NULL DEFAULT '',
			embedding_model_id    TEXT NOT NULL DEFAULT '',

			-- v2.1: event timing (when the described event happened, not when fact was created)
			event_start_at   INTEGER NOT NULL DEFAULT 0,
			event_end_at     INTEGER NOT NULL DEFAULT 0,

			created_at       INTEGER NOT NULL,
			updated_at       INTEGER NOT NULL
		)`,

		// ── reflections (L1.5: fact synthesis → pending → confirmed → promoted → persona) ──
		`CREATE TABLE IF NOT EXISTS reflections (
			id               INTEGER PRIMARY KEY AUTOINCREMENT,
			schema_version   INTEGER NOT NULL DEFAULT 1,
			text             TEXT    NOT NULL DEFAULT '',
			entity           TEXT    NOT NULL DEFAULT 'relationship',
			relation_type    TEXT,
			status           TEXT    NOT NULL DEFAULT 'pending',
			source_fact_ids  TEXT    NOT NULL DEFAULT '[]',
			reinforcement    REAL    NOT NULL DEFAULT 0,
			rein_last_signal_at TEXT,
			disputation      REAL    NOT NULL DEFAULT 0,
			disp_last_signal_at TEXT,
			feedback         TEXT,
			next_eligible_at TEXT,
			absorbed_into    INTEGER DEFAULT NULL,
			suppress         INTEGER NOT NULL DEFAULT 0,
			mention_count    INTEGER NOT NULL DEFAULT 0,
			vector           BLOB,
			embedding_text_sha256 TEXT NOT NULL DEFAULT '',
			embedding_model_id    TEXT NOT NULL DEFAULT '',
			created_at       INTEGER NOT NULL,
			updated_at       INTEGER NOT NULL
		)`,

		// ── diaries (L1 episodic: generated by Reflection+Diary joint pipeline) ──
		`CREATE TABLE IF NOT EXISTS diaries (
			id              INTEGER PRIMARY KEY AUTOINCREMENT,
			schema_version  INTEGER NOT NULL DEFAULT 1,
			title           TEXT    NOT NULL DEFAULT '',
			summary         TEXT    NOT NULL DEFAULT '',
			emotion_valence REAL    NOT NULL DEFAULT 0,
			emotion_arousal REAL    NOT NULL DEFAULT 0,
			emotion_primary TEXT    NOT NULL DEFAULT '',
			vector          BLOB,
			topic_id        INTEGER DEFAULT NULL,
			reflection_id   INTEGER DEFAULT NULL,
			abstracted      INTEGER NOT NULL DEFAULT 0,
			archived        INTEGER NOT NULL DEFAULT 0,
			created_at      INTEGER NOT NULL
		)`,

		// ── strategies (L3 distilled heuristics) ──
		`CREATE TABLE IF NOT EXISTS strategies (
			id              INTEGER PRIMARY KEY AUTOINCREMENT,
			schema_version  INTEGER NOT NULL DEFAULT 1,
			situation       TEXT    NOT NULL DEFAULT '',
			good_strategy   TEXT    NOT NULL DEFAULT '',
			bad_strategy    TEXT    NOT NULL DEFAULT '',
			reason          TEXT    NOT NULL DEFAULT '',
			confidence      REAL    NOT NULL DEFAULT 0.5,
			source          TEXT    NOT NULL DEFAULT '',
			vector          BLOB,
			active          INTEGER NOT NULL DEFAULT 1,
			created_at      INTEGER NOT NULL,
			updated_at      INTEGER NOT NULL
		)`,

		// ── messages (chat history) ──
		`CREATE TABLE IF NOT EXISTS messages (
			id         INTEGER PRIMARY KEY AUTOINCREMENT,
			role       TEXT    NOT NULL,
			content    TEXT    NOT NULL DEFAULT '',
			images     TEXT    NOT NULL DEFAULT '[]',
			meta_json  TEXT    NOT NULL DEFAULT '{}',
			created_at INTEGER NOT NULL
		)`,

		// Persistent cursor prevents MemoryWorker from replaying the same
		// history window after every wake or process restart.
		`CREATE TABLE IF NOT EXISTS memory_worker_state (
			key        TEXT PRIMARY KEY,
			value_int  INTEGER NOT NULL DEFAULT 0,
			updated_at INTEGER NOT NULL
		)`,

		// Auditable provenance for facts extracted from chat messages.
		`CREATE TABLE IF NOT EXISTS fact_sources (
			fact_id    INTEGER NOT NULL,
			message_id INTEGER NOT NULL,
			created_at INTEGER NOT NULL,
			PRIMARY KEY (fact_id, message_id),
			FOREIGN KEY(fact_id) REFERENCES facts(id),
			FOREIGN KEY(message_id) REFERENCES messages(id)
		)`,

		// Every automatic fact merge is retained for inspection and rollback
		// analysis. Incoming content is never silently discarded.
		`CREATE TABLE IF NOT EXISTS fact_merge_audit (
			id                     INTEGER PRIMARY KEY AUTOINCREMENT,
			target_fact_id         INTEGER NOT NULL,
			incoming_entity        TEXT NOT NULL,
			incoming_relation_type TEXT NOT NULL,
			incoming_content       TEXT NOT NULL,
			reason                 TEXT NOT NULL,
			similarity             REAL NOT NULL,
			created_at             INTEGER NOT NULL,
			FOREIGN KEY(target_fact_id) REFERENCES facts(id)
		)`,

		// ── episodes (topic-grouped conversations) ──
		`CREATE TABLE IF NOT EXISTS episodes (
			id         INTEGER PRIMARY KEY AUTOINCREMENT,
			topic      TEXT    NOT NULL DEFAULT '',
			summary    TEXT    NOT NULL DEFAULT '',
			status     TEXT    NOT NULL DEFAULT 'active',
			created_at INTEGER NOT NULL,
			updated_at INTEGER NOT NULL
		)`,

		// ── topics (semantic clusters) ──
		`CREATE TABLE IF NOT EXISTS topics (
			id       INTEGER PRIMARY KEY AUTOINCREMENT,
			name     TEXT    NOT NULL DEFAULT '',
			centroid BLOB,
			count    INTEGER NOT NULL DEFAULT 0
		)`,

		// ── conversation_threads (cross-session topic tracking) ──
		`CREATE TABLE IF NOT EXISTS conversation_threads (
			id              INTEGER PRIMARY KEY AUTOINCREMENT,
			schema_version  INTEGER NOT NULL DEFAULT 1,
			type            TEXT    NOT NULL DEFAULT '',
			goal            TEXT    NOT NULL DEFAULT '',
			status          TEXT    NOT NULL DEFAULT 'active',
			priority        REAL    NOT NULL DEFAULT 0.5,
			best_approach   TEXT    NOT NULL DEFAULT '',
			outcome         TEXT    NOT NULL DEFAULT '',
			learnings       TEXT    NOT NULL DEFAULT '',
			created_at      INTEGER NOT NULL,
			updated_at      INTEGER NOT NULL
		)`,

		// ── outcomes (action → result tracking, feeds Learner + user model) ──
		`CREATE TABLE IF NOT EXISTS outcomes (
			id              INTEGER PRIMARY KEY AUTOINCREMENT,
			schema_version  INTEGER NOT NULL DEFAULT 1,
			action_source   TEXT    NOT NULL DEFAULT '',
			action_type     TEXT    NOT NULL DEFAULT '',
			hour_of_day     INTEGER NOT NULL DEFAULT 0,
			day_of_week     INTEGER NOT NULL DEFAULT 0,
			app_context     TEXT    NOT NULL DEFAULT '',
			emotion_bucket  TEXT    NOT NULL DEFAULT '',
			escalation_lvl  INTEGER NOT NULL DEFAULT 0,
			outcome         INTEGER NOT NULL DEFAULT 0,
			response_delay  INTEGER NOT NULL DEFAULT 0,
			created_at      INTEGER NOT NULL
		)`,

		// ── drive_records (decision-time snapshot for DPO batch learning) ──
		`CREATE TABLE IF NOT EXISTS drive_records (
			id       INTEGER PRIMARY KEY AUTOINCREMENT,
			action   TEXT  NOT NULL DEFAULT '',
			social   REAL  NOT NULL DEFAULT 0,
			care     REAL  NOT NULL DEFAULT 0,
			curious  REAL  NOT NULL DEFAULT 0,
			quiet    REAL  NOT NULL DEFAULT 0,
			explore  REAL  NOT NULL DEFAULT 0,
			reward   REAL  NOT NULL DEFAULT 0,
			at       INTEGER NOT NULL
		)`,

		// ── proactive policy audit trail ───────────────────────────────
		`CREATE TABLE IF NOT EXISTS proactive_decisions (
			decision_id     TEXT PRIMARY KEY,
			policy_version  TEXT NOT NULL,
			action          TEXT NOT NULL,
			source          TEXT NOT NULL,
			score           REAL NOT NULL,
			context_json    TEXT NOT NULL,
			candidates_json TEXT NOT NULL,
			content         TEXT NOT NULL DEFAULT '',
			state           TEXT NOT NULL DEFAULT 'delivered',
			created_at      INTEGER NOT NULL,
			delivered_at    INTEGER NOT NULL,
			resolved_at     INTEGER NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS proactive_feedback (
			id          INTEGER PRIMARY KEY AUTOINCREMENT,
			decision_id TEXT NOT NULL,
			kind        TEXT NOT NULL,
			reward      REAL NOT NULL,
			source      TEXT NOT NULL,
			confidence  REAL NOT NULL,
			note        TEXT NOT NULL DEFAULT '',
			created_at  INTEGER NOT NULL,
			FOREIGN KEY(decision_id) REFERENCES proactive_decisions(decision_id)
		)`,
		`CREATE TABLE IF NOT EXISTS proactive_feedback_requests (
			event_id    TEXT PRIMARY KEY,
			decision_id TEXT NOT NULL,
			created_at  INTEGER NOT NULL,
			FOREIGN KEY(decision_id) REFERENCES proactive_decisions(decision_id)
		)`,
		`CREATE TABLE IF NOT EXISTS proactive_feedback_current (
			decision_id TEXT PRIMARY KEY,
			event_id    TEXT NOT NULL,
			kind        TEXT NOT NULL,
			reward      REAL NOT NULL,
			source      TEXT NOT NULL,
			confidence  REAL NOT NULL,
			note        TEXT NOT NULL DEFAULT '',
			created_at  INTEGER NOT NULL,
			FOREIGN KEY(decision_id) REFERENCES proactive_decisions(decision_id)
		)`,
		`CREATE TABLE IF NOT EXISTS proactive_replies (
			decision_id TEXT PRIMARY KEY,
			content TEXT NOT NULL DEFAULT '',
			attribution TEXT NOT NULL,
			confidence REAL NOT NULL,
			created_at INTEGER NOT NULL,
			FOREIGN KEY(decision_id) REFERENCES proactive_decisions(decision_id)
		)`,
		`CREATE TABLE IF NOT EXISTS proactive_controls (
			scope       TEXT NOT NULL,
			scope_value TEXT NOT NULL DEFAULT '',
			mode        TEXT NOT NULL,
			until_at    INTEGER NOT NULL DEFAULT 0,
			source      TEXT NOT NULL,
			updated_at  INTEGER NOT NULL,
			PRIMARY KEY(scope, scope_value)
		)`,

		// ── events (append-only audit log, v2.1) ──
		`CREATE TABLE IF NOT EXISTS events (
			id          INTEGER PRIMARY KEY AUTOINCREMENT,
			type        TEXT    NOT NULL,
			entity_id   INTEGER NOT NULL,
			entity_kind TEXT    NOT NULL,
			payload     TEXT    NOT NULL DEFAULT '{}',
			created_at  INTEGER NOT NULL
		)`,

		// ── FTS5 indexes ──
		`CREATE VIRTUAL TABLE IF NOT EXISTS facts_fts USING fts5(
			content, entity, relation_type,
			content='facts', content_rowid='id'
		)`,

		`CREATE VIRTUAL TABLE IF NOT EXISTS diaries_fts USING fts5(
			title, summary,
			content='diaries', content_rowid='id'
		)`,

		`CREATE VIRTUAL TABLE IF NOT EXISTS reflections_fts USING fts5(
			text, entity, relation_type,
			content='reflections', content_rowid='id'
		)`,

		// ── Indexes ──
		`CREATE INDEX IF NOT EXISTS idx_facts_entity ON facts(entity)`,
		`CREATE INDEX IF NOT EXISTS idx_facts_relation ON facts(relation_type)`,
		`CREATE INDEX IF NOT EXISTS idx_facts_source_tier ON facts(source_tier)`,
		`CREATE INDEX IF NOT EXISTS idx_facts_archived ON facts(archived)`,
		`CREATE INDEX IF NOT EXISTS idx_facts_created ON facts(created_at)`,
		`CREATE INDEX IF NOT EXISTS idx_facts_signal ON facts(signal_processed, archived)`,
		`CREATE INDEX IF NOT EXISTS idx_facts_absorbed ON facts(absorbed)`,
		`CREATE INDEX IF NOT EXISTS idx_facts_entity_rel ON facts(entity, relation_type)`,
		`CREATE INDEX IF NOT EXISTS idx_reflections_status ON reflections(status)`,
		`CREATE INDEX IF NOT EXISTS idx_reflections_entity ON reflections(entity)`,
		`CREATE INDEX IF NOT EXISTS idx_diaries_created ON diaries(created_at)`,
		`CREATE INDEX IF NOT EXISTS idx_diaries_archived ON diaries(archived)`,
		`CREATE INDEX IF NOT EXISTS idx_messages_created ON messages(created_at)`,
		`CREATE INDEX IF NOT EXISTS idx_fact_sources_message ON fact_sources(message_id)`,
		`CREATE INDEX IF NOT EXISTS idx_fact_merge_target ON fact_merge_audit(target_fact_id, created_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_threads_status ON conversation_threads(status)`,
		`CREATE INDEX IF NOT EXISTS idx_outcomes_source ON outcomes(action_source)`,
		`CREATE INDEX IF NOT EXISTS idx_proactive_decisions_state ON proactive_decisions(state, delivered_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_proactive_feedback_decision ON proactive_feedback(decision_id, created_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_proactive_replies_created ON proactive_replies(created_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_proactive_controls_until ON proactive_controls(until_at)`,
		`CREATE INDEX IF NOT EXISTS idx_outcomes_created ON outcomes(created_at)`,
		`CREATE INDEX IF NOT EXISTS idx_events_type ON events(type)`,
		`CREATE INDEX IF NOT EXISTS idx_events_created ON events(created_at)`,
		`CREATE INDEX IF NOT EXISTS idx_events_entity ON events(entity_kind, entity_id)`,

		// ── Data migrations ──
		`UPDATE facts SET memcell_type = 'fact' WHERE memcell_type = '' OR memcell_type IS NULL`,
	}

	for _, m := range migrations {
		if _, err := s.db.Exec(m); err != nil {
			return fmt.Errorf("migration: %w\nSQL: %.80s", err, m)
		}
	}

	return nil
}
