// Package app contains the Launcher (lifecycle orchestrator) and Wire DI definitions.
//
// Files:
//   launcher.go — SionLauncher: start phases 0-4, stop in reverse, signal handling
//   wire.go     — Wire provider sets (InfraSet, DomainSet, ServiceSets, TransportSet)
//   wire_gen.go — AUTO-GENERATED by `wire`. Do not edit manually.

package app

// TODO (module 23): Implement SionLauncher
//   - Phase 0: ConfigManager → Logger → SQLite → LLMGateway → EmbeddingService
//   - Phase 1: MemoryService | EmotionService | PerceptionService | IdentityService (parallel)
//   - Phase 2: ChatService | CognitionService | CareService | ProactiveService (depends on Phase 1)
//   - Phase 3: HTTP Server → start accepting requests
//   - Phase 4: Plugins (parallel, depends on Phase 2)
//   - Stop: reverse order, each with 10s timeout

// TODO (module 23): Wire integration
//   - go install google/wire
//   - Edit wire.go to add provider sets
//   - Run `wire` to generate wire_gen.go
